### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by abjerner** [limbo-works/Limbo.Umbraco.Feedback#1]
Misc. ideas for potential features. Not necessarily anything that is prioritized or that we're working on.

```[tasklist]
### Tasks
- [ ] Feature to delete all entries before a given date
- [ ] Feature to anonymize name and email for all entries before a given date
- [ ] Statistics
- [ ] Batch operations
- [ ] A way to view archived entries
```
